### ISSUE TITLE
SVLEN Log Scale Visualizations

### ISSUE THREAD

**Issue by seantruong** [PacificBiosciences/HiFi-SVTopo#1]
Great tool Jon! Might I suggest making the visuals of SVLEN be on log-scale? That way we can still see a 10bp event alongside a 10kbp or even 1Mbp event. This is what LINX does with their circos visualization. https://github.com/hartwigmedical/hmftools/blob/master/linx/README.md#visualisation

Try it out with the example you have here, and the 11bp INV (segment D) will pop out: https://github.com/PacificBiosciences/HiFi-SVTopo/blob/main/docs/imgs/translocation.png

**Comment by jbelyeu** [comment]
Hey Sean, great to hear from you! TBH I've found the LINX visualization scaling somewhat confusing, or at least less intuitive. The track at the bottom of the svtopo plot with block sizes standardized is intended to address the same issue in a simpler way, allowing the main window to focus on a general representation of the larger rearrangement. There appears to be an ordering artifact in that specific one that I hadn't noticed, though, so thanks for pointing it out!
